# Generated by Django 3.1a1 on 2020-05-27 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('display', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='crop',
            old_name='cropname',
            new_name='cityname',
        ),
        migrations.RemoveField(
            model_name='crop',
            name='weather',
        ),
        migrations.AddField(
            model_name='crop',
            name='humidity',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='ph',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='rainfall',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='crop',
            name='temperature',
            field=models.FloatField(default=30),
            preserve_default=False,
        ),
    ]
